-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE billing.plans (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  base_price numeric NOT NULL DEFAULT 0,
  base_limits jsonb,
  features jsonb,
  is_active boolean NOT NULL DEFAULT false,
  order real NOT NULL DEFAULT 0,
  trial_days smallint NOT NULL DEFAULT 0,
  tier_level smallint NOT NULL DEFAULT 0,
  CONSTRAINT plans_pkey PRIMARY KEY (id)
);
CREATE TABLE billing.plan_periods (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  months smallint NOT NULL,
  discount_percentage numeric NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT false,
  CONSTRAINT plan_periods_pkey PRIMARY KEY (id)
);
CREATE TABLE billing.addons (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  type text NOT NULL,
  unit_quantity smallint NOT NULL DEFAULT 1,
  max_quantity smallint,
  is_active boolean NOT NULL DEFAULT false,
  CONSTRAINT addons_pkey PRIMARY KEY (id)
);
CREATE TABLE billing.addon_prices (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  addon_id bigint NOT NULL,
  plan_id bigint,
  price_per_unit numeric NOT NULL,
  is_active boolean NOT NULL DEFAULT false,
  CONSTRAINT addon_prices_pkey PRIMARY KEY (id),
  CONSTRAINT addon_prices_addon_id_fkey FOREIGN KEY (addon_id) REFERENCES billing.addons(id),
  CONSTRAINT addon_prices_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES billing.plans(id)
);
CREATE TABLE billing.subscriptions (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  account_id bigint NOT NULL,
  plan_id bigint NOT NULL,
  plan_period_id bigint,
  period_months smallint,
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  trial_start_date timestamp with time zone,
  trial_end_date timestamp with time zone,
  status text NOT NULL DEFAULT 'pending'::text,
  base_price numeric NOT NULL DEFAULT 0,
  base_price_with_discount numeric NOT NULL DEFAULT 0,
  addons_total numeric NOT NULL DEFAULT 0,
  total_price numeric NOT NULL DEFAULT 0,
  total_limits jsonb,
  payment_status text,
  payment_method text,
  next_due_date timestamp with time zone,
  cancelled_at timestamp with time zone,
  cancel_requested_at timestamp with time zone,
  cancel_reason text,
  system_cancel_reason text,
  is_granted boolean NOT NULL DEFAULT false,
  granted_by_user_id uuid,
  management_type text DEFAULT 'platform'::text,
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES billing.plans(id),
  CONSTRAINT subscriptions_plan_period_id_fkey FOREIGN KEY (plan_period_id) REFERENCES billing.plan_periods(id),
  CONSTRAINT subscriptions_granted_by_user_id_fkey FOREIGN KEY (granted_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE billing.subscription_addons (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  subscription_id bigint NOT NULL,
  addon_id bigint NOT NULL,
  quantity smallint NOT NULL DEFAULT 1,
  unit_price numeric NOT NULL,
  total_price numeric NOT NULL,
  discount_percentage numeric NOT NULL DEFAULT 0,
  unit_quantity smallint DEFAULT 1,
  CONSTRAINT subscription_addons_pkey PRIMARY KEY (id),
  CONSTRAINT subscription_addons_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES billing.subscriptions(id),
  CONSTRAINT subscription_addons_addon_id_fkey FOREIGN KEY (addon_id) REFERENCES billing.addons(id)
);
CREATE TABLE billing.payments (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  subscription_id bigint NOT NULL,
  description text,
  value numeric NOT NULL,
  discount_value numeric,
  discount_type text,
  due_date timestamp with time zone NOT NULL,
  payment_date timestamp with time zone,
  confirmed_date timestamp with time zone,
  status text NOT NULL,
  payment_method text,
  asaas_payment_id text NOT NULL,
  asaas_invoice_url text,
  asaas_transaction_receipt_url text,
  failure_reason text,
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES billing.subscriptions(id)
);

-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.accounts (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  status text DEFAULT 'active'::text,
  created_by_user_id uuid DEFAULT auth.uid(),
  currency text DEFAULT 'brl'::text,
  address text,
  address_complement text,
  address_number text,
  city text,
  state text,
  zip_code text,
  cnpj text,
  phone text,
  asaas_customer_id text,
  has_used_trial boolean NOT NULL DEFAULT false,
  phone_details jsonb,
  email text,
  extra_features jsonb,
  CONSTRAINT accounts_pkey PRIMARY KEY (id),
  CONSTRAINT accounts_created_by_user_id_fkey1 FOREIGN KEY (created_by_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.channels (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NOT NULL,
  type USER-DEFINED NOT NULL,
  status text DEFAULT ''::text,
  phone text,
  created_by_user_id uuid,
  pipeline_id bigint,
  account_id bigint NOT NULL,
  config jsonb,
  connected_at timestamp with time zone,
  is_active boolean NOT NULL DEFAULT true,
  ignored_contacts ARRAY,
  last_disconnected_at timestamp with time zone,
  last_disconnected_reason text,
  identifier text,
  CONSTRAINT channels_pkey PRIMARY KEY (id),
  CONSTRAINT channels_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT channels_creator_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id),
  CONSTRAINT channels_pipeline_id_fkey FOREIGN KEY (pipeline_id) REFERENCES public.pipelines(id)
);
CREATE TABLE public.conversations (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  status text NOT NULL DEFAULT 'in_progress'::text,
  channel_id bigint,
  person_id bigint,
  deal_id bigint,
  account_id bigint NOT NULL,
  created_by_user_id uuid,
  last_message_at timestamp with time zone,
  reply_to text,
  viewed_at timestamp with time zone DEFAULT now(),
  channel_phone text,
  channel_type USER-DEFINED,
  follow_up_count smallint DEFAULT 0,
  is_paused boolean NOT NULL DEFAULT false,
  intent text,
  summary text,
  agent_id bigint,
  channel_identifier text,
  contact_identifier text,
  ai_stage text CHECK (ai_stage = ANY (ARRAY['qualifying'::text, 'scheduling'::text])),
  CONSTRAINT conversations_pkey PRIMARY KEY (id),
  CONSTRAINT conversations_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT conversations_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id),
  CONSTRAINT conversations_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.persons(id),
  CONSTRAINT conversations_channel_id_fkey FOREIGN KEY (channel_id) REFERENCES public.channels(id),
  CONSTRAINT conversations_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES public.deals(id),
  CONSTRAINT conversations_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(id)
);
CREATE TABLE public.deals (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NOT NULL,
  value numeric,
  order real,
  status text NOT NULL DEFAULT 'open'::text,
  origin text,
  won_time timestamp with time zone,
  lost_time timestamp with time zone,
  created_by_user_id uuid DEFAULT auth.uid(),
  owner_user_id uuid,
  person_id bigint NOT NULL,
  pipeline_stage_id bigint NOT NULL,
  additional_info text,
  account_id bigint NOT NULL,
  pipeline_id bigint NOT NULL,
  lost_reason text,
  updated_by uuid DEFAULT auth.uid(),
  is_active boolean NOT NULL DEFAULT true,
  blocked_at timestamp with time zone,
  blocked_reason text,
  qualification_status text,
  qualification_updated_at timestamp with time zone,
  qualification_updated_by uuid,
  CONSTRAINT deals_pkey PRIMARY KEY (id),
  CONSTRAINT deals_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT deals_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.persons(id),
  CONSTRAINT deals_pipeline_stage_id_fkey FOREIGN KEY (pipeline_stage_id) REFERENCES public.pipeline_stages(id),
  CONSTRAINT deals_pipeline_id_fkey FOREIGN KEY (pipeline_id) REFERENCES public.pipelines(id),
  CONSTRAINT deals_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id),
  CONSTRAINT deals_qualification_updated_by_fkey FOREIGN KEY (qualification_updated_by) REFERENCES public.users(id),
  CONSTRAINT deals_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id),
  CONSTRAINT deals_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.deals_tags (
  deal_id bigint NOT NULL,
  tag_id bigint NOT NULL,
  CONSTRAINT deals_tags_pkey PRIMARY KEY (deal_id, tag_id),
  CONSTRAINT deals_tags_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES public.deals(id),
  CONSTRAINT deals_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.tags(id)
);
CREATE TABLE public.messages (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  viewed_at timestamp with time zone,
  content jsonb,
  direction text NOT NULL,
  reaction text,
  type USER-DEFINED NOT NULL,
  sender_type text NOT NULL,
  sender_id text,
  replied_to_message_id text,
  conversation_id bigint NOT NULL,
  api_message_id text,
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id)
);
CREATE TABLE public.organizations (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NOT NULL,
  cnpj text,
  state text,
  city text,
  address text,
  additional_info text,
  created_by_user_id uuid,
  account_id bigint NOT NULL,
  CONSTRAINT organizations_pkey PRIMARY KEY (id),
  CONSTRAINT organizations_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT organizations_creator_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.person_emails (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  label text NOT NULL,
  email text NOT NULL,
  person_id bigint NOT NULL,
  is_primary boolean NOT NULL DEFAULT false,
  CONSTRAINT person_emails_pkey PRIMARY KEY (id),
  CONSTRAINT person_emails_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.persons(id)
);
CREATE TABLE public.person_phones (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  phone text NOT NULL,
  country_code text NOT NULL,
  is_primary boolean NOT NULL DEFAULT false,
  person_id bigint NOT NULL,
  label text,
  full_phone text NOT NULL,
  CONSTRAINT person_phones_pkey PRIMARY KEY (id),
  CONSTRAINT person_phones_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.persons(id)
);
CREATE TABLE public.person_socials (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  person_id bigint NOT NULL UNIQUE,
  facebook text,
  instagram text,
  linkedin text,
  x text,
  youtube text,
  CONSTRAINT person_socials_pkey PRIMARY KEY (id),
  CONSTRAINT person_socials_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.persons(id)
);
CREATE TABLE public.persons (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by_user_id uuid DEFAULT auth.uid(),
  name text NOT NULL,
  photo text,
  occupation text,
  state text,
  city text,
  address text,
  additional_info text,
  organization_id bigint,
  account_id bigint NOT NULL,
  updated_by uuid DEFAULT auth.uid(),
  CONSTRAINT persons_pkey PRIMARY KEY (id),
  CONSTRAINT persons_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT persons_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT persons_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id),
  CONSTRAINT persons_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.pipeline_stages (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NOT NULL,
  order real,
  pipeline_id bigint NOT NULL,
  color text NOT NULL,
  type text,
  CONSTRAINT pipeline_stages_pkey PRIMARY KEY (id),
  CONSTRAINT pipeline_stages_pipeline_id_fkey FOREIGN KEY (pipeline_id) REFERENCES public.pipelines(id)
);
CREATE TABLE public.pipelines (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  created_by_user_id uuid DEFAULT auth.uid(),
  account_id bigint NOT NULL,
  owner_user_id uuid,
  CONSTRAINT pipelines_pkey PRIMARY KEY (id),
  CONSTRAINT pipelines_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT pipelines_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id),
  CONSTRAINT pipelines_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.roles (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NOT NULL UNIQUE,
  description text,
  slug text NOT NULL UNIQUE,
  access_level smallint DEFAULT 0,
  permissions jsonb,
  CONSTRAINT roles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tags (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NOT NULL,
  color text,
  account_id bigint NOT NULL,
  CONSTRAINT tags_pkey PRIMARY KEY (id),
  CONSTRAINT tags_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id)
);
CREATE TABLE public.tasks (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  finished_at timestamp with time zone,
  due_time timestamp with time zone,
  name text NOT NULL,
  description text,
  status text,
  deal_id bigint,
  owner_user_id uuid DEFAULT auth.uid(),
  updated_by uuid DEFAULT auth.uid(),
  account_id bigint,
  type text NOT NULL DEFAULT 'todo'::text CHECK (type = ANY (ARRAY['todo'::text, 'meeting'::text])),
  CONSTRAINT tasks_pkey PRIMARY KEY (id),
  CONSTRAINT tasks_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES public.deals(id),
  CONSTRAINT tasks_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES public.users(id),
  CONSTRAINT tasks_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id),
  CONSTRAINT tasks_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT auth.uid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text,
  slug text NOT NULL UNIQUE,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by_user_id uuid,
  account_id bigint,
  photo text,
  role_id bigint,
  email character varying NOT NULL,
  status text NOT NULL DEFAULT 'active'::text,
  last_sign_in_at timestamp with time zone,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT users_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id)
);
CREATE TABLE public.account_invitations (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone NOT NULL,
  email character varying NOT NULL,
  token text NOT NULL UNIQUE,
  status text NOT NULL,
  account_id bigint NOT NULL,
  photo text,
  role_id bigint NOT NULL,
  name text NOT NULL,
  account_name text,
  CONSTRAINT account_invitations_pkey PRIMARY KEY (id),
  CONSTRAINT account_invitations_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT account_invitations_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id)
);
CREATE TABLE public.agents (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  channel_id bigint,
  webhook_url text,
  name text,
  channel_phone text,
  account_id bigint,
  instructions text,
  status text,
  office_hours_start time with time zone,
  office_hours_end time with time zone,
  follow_up_limit smallint,
  follow_up_interval smallint,
  ai_name text,
  engine text,
  about_instructions text,
  ai_model text DEFAULT 'openai'::text,
  channel_identifier text,
  account_name text,
  scheduling_enabled boolean NOT NULL DEFAULT false,
  calendar_id text,
  calendar_verified boolean NOT NULL DEFAULT false,
  meeting_duration_minutes smallint NOT NULL DEFAULT 60,
  meeting_interval_minutes smallint NOT NULL DEFAULT 60,
  scheduling_hours_start time with time zone,
  scheduling_hours_end time with time zone,
  scheduling_week_days ARRAY NOT NULL DEFAULT '{1,2,3,4,5}'::smallint[] CHECK (scheduling_week_days <@ ARRAY[1::smallint, 2::smallint, 3::smallint, 4::smallint, 5::smallint, 6::smallint, 7::smallint]),
  meeting_title text,
  meeting_description text,
  meeting_confirmation_message text,
  reminder_enabled boolean NOT NULL DEFAULT true,
  reminder_minutes smallint NOT NULL DEFAULT 10,
  scheduling_blocked_times jsonb NOT NULL DEFAULT '["12:00"]'::jsonb,
  scheduling_blocked_dates jsonb NOT NULL DEFAULT '[]'::jsonb,
  office_week_days ARRAY NOT NULL DEFAULT '{1,2,3,4,5}'::smallint[] CHECK (office_week_days <@ ARRAY[1::smallint, 2::smallint, 3::smallint, 4::smallint, 5::smallint, 6::smallint, 7::smallint]),
  CONSTRAINT agents_pkey PRIMARY KEY (id),
  CONSTRAINT agents_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT agents_channel_id_fkey FOREIGN KEY (channel_id) REFERENCES public.channels(id)
);
CREATE TABLE public.messages_queue (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  message_id text NOT NULL,
  conversation_id bigint NOT NULL,
  CONSTRAINT messages_queue_pkey PRIMARY KEY (id)
);
CREATE TABLE public.users_accounts (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id uuid NOT NULL,
  account_id bigint NOT NULL,
  role_id bigint NOT NULL,
  granted_by_user_id uuid DEFAULT auth.uid(),
  CONSTRAINT users_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT users_accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT users_accounts_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT users_accounts_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id),
  CONSTRAINT users_accounts_granted_by_user_id_fkey FOREIGN KEY (granted_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.debug_logs (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  type text NOT NULL,
  content jsonb NOT NULL,
  created_by_user_id uuid DEFAULT auth.uid(),
  CONSTRAINT debug_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.conversation_ai_sessions (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  conversation_id bigint NOT NULL UNIQUE,
  agent_id bigint,
  ai_stage text,
  ai_status text,
  ai_added_tags ARRAY,
  qualification_status text,
  qualification_updated_at timestamp with time zone,
  qualification_reason text,
  greeting_sent boolean,
  intent text,
  summary text,
  questions_answered jsonb,
  follow_up_count smallint DEFAULT 0,
  last_follow_up_at timestamp with time zone,
  waiting_until timestamp with time zone,
  waiting_reason text,
  error_message text,
  ended_at timestamp with time zone,
  CONSTRAINT conversation_ai_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT conversation_ai_sessions_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id),
  CONSTRAINT conversation_ai_sessions_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(id)
);
CREATE TABLE public.person_identifiers (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  account_id bigint NOT NULL,
  person_id bigint NOT NULL,
  channel_type text NOT NULL CHECK (channel_type = ANY (ARRAY['whatsapp'::text, 'instagram'::text, 'telegram'::text, 'email'::text])),
  identifier_type text NOT NULL CHECK (identifier_type = ANY (ARRAY['jid'::text, 'lid'::text, 'phone'::text, 'email'::text, 'username'::text, 'user_id'::text])),
  identifier text NOT NULL,
  is_primary boolean NOT NULL DEFAULT false,
  CONSTRAINT person_identifiers_pkey PRIMARY KEY (id),
  CONSTRAINT person_identifiers_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT person_identifiers_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.persons(id)
);
CREATE TABLE public.task_events (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  task_id bigint NOT NULL UNIQUE,
  starts_at timestamp with time zone NOT NULL,
  ends_at timestamp with time zone NOT NULL,
  meeting_url text,
  provider text,
  external_event_id text,
  sync_status text NOT NULL DEFAULT 'synced'::text CHECK (sync_status = ANY (ARRAY['pending'::text, 'synced'::text, 'error'::text])),
  sync_error text,
  last_synced_at timestamp with time zone,
  etag text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT task_events_pkey PRIMARY KEY (id),
  CONSTRAINT task_events_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tasks(id)
);